version: '3.8'
services:
  db:
    image: 'postgres:latest'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  rails:
    build: ./ 
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/docker/app
    depends_on:
      - db
  # frontend:
  #   build: ./frontend/
  #   ports:
  #     - '5173:5173'
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules

volumes:
  postgres:
